### ISSUE TITLE
When I run the program, I encounter the error: DLL load failed while importing _C: The specified module could not be found.

### ISSUE THREAD

**Issue by LijieJia** [SarahWeiii/diso#10]
When I run the program, I encounter the error: DLL load failed while importing _C: The specified module could not be found.

**Comment by LijieJia** [comment]
It also can be ImportError: cannot import name '_C' from partially initialized module 'diso' (most likely due to a circular import) ImportError: cannot import name '_C' from partially initialized module 'diso' (most likely due to a circular import)

**Comment by SarahWeiii** [comment]
Can you share more info about the OS, GPU and cuda version?

**Comment by Fen9** [comment]
same problem
`/opt/conda/lib/python3.10/site-packages/diso/_C.so: undefined symbol: _ZN4cumc4CuMCIfiE7forwardEPKfPKNS_6VertexIfEEiiifi`
OS: ubuntu 20.04, CUDA=12.1, GPU:A100

**Comment by LijieJia** [comment]
Thank you for the response. I solved the issue by setting compiler flags, specifically the `nvcc_flags`. I hope this helps you.

**Comment by Moondok** [comment]
@LijieJia Hi, I met the totally same problem, could you please specify that how to fix that by setting compiler flags? Thanks in advance.
