### ISSUE TITLE
batched training with DiffMC

### ISSUE THREAD

**Issue by ashawkey** [SarahWeiii/diso#2]
Hi, thanks for sharing this amazing implementation!

I have a question about batched training with diso. 
It seems current implementation saves internal states (e.g., `used_to_first_mc_tri`, `used_cell_code`) inside the `mc` struct, which makes it unable to performed batched forward & backward even with a for loop. For example:
```python
loss = 0
for b in range(B):
    v, f = diffmc(sdf[b], deform[b]) # forward multiple times, only the last state is recorded
    loss = loss + loss_func(v)
loss.backward() # wrong gradient, all backwards use the state of the last batch
```
I wonder is there any workaround to make this work? 
For example, maybe move all internal variables outside the struct and into the context of torch `Function`?

**Comment by SarahWeiii** [comment]
There are two possible ways to achieve batch training:
1. Create multiple iso-surface extractor and parallelly use them by `stream`
2. Concat the sdfs into a whole one and directly put it into the iso-surface extractor, generating a goup of meshes, then you need to crop each mesh by the corresponding offsets

**Comment by ashawkey** [comment]
Thanks for the quick reply! Creating multiple instances work for me.
